import { and, desc, eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { z } from "zod";
import { announcements, historyEntries, mediaAssets, questionsAnswers, resources, subjects } from "../../drizzle/schema";
import { getDb } from "../db";
import { router } from "../_core/trpc";
import { ownerProcedure } from "./guards";

async function databaseOrThrow() { const database = await getDb(); if (!database) throw new Error("Database is not available"); return database; }
async function assertSubject(ownerId: number, subjectId: number) { const database = await databaseOrThrow(); const row = await database.select({ id: subjects.id }).from(subjects).where(and(eq(subjects.id, subjectId), eq(subjects.ownerId, ownerId))).limit(1); if (!row[0]) throw new Error("Subject not found"); return database; }
async function assertPublicMedia(db: Awaited<ReturnType<typeof databaseOrThrow>>, ownerId: number, assetId?: number | null) { if (!assetId) return null; const row = await db.select({ id: mediaAssets.id }).from(mediaAssets).where(and(eq(mediaAssets.id, assetId), eq(mediaAssets.ownerId, ownerId), eq(mediaAssets.publicUse, true))).limit(1); if (!row[0]) throw new Error("Public media must be an owned asset marked for public use"); return assetId; }
const subjectInput = z.object({ subjectId: z.number().int().positive() });
const publicMediaInput = z.number().int().positive().nullable().optional();
const updateSummary = z.string().trim().min(3).max(280);

export const contentRouter = router({
  announcements: router({
    list: ownerProcedure.input(subjectInput).query(async ({ ctx, input }) => (await assertSubject(ctx.user.id, input.subjectId)).select().from(announcements).where(eq(announcements.subjectId, input.subjectId)).orderBy(desc(announcements.updatedAt))),
    create: ownerProcedure.input(subjectInput.extend({ title: z.string().trim().min(2).max(220), body: z.string().trim().min(1).max(20000), mediaAssetId: publicMediaInput, socialPreviewMediaAssetId: publicMediaInput })).mutation(async ({ ctx, input }) => { const db = await assertSubject(ctx.user.id, input.subjectId); await assertPublicMedia(db, ctx.user.id, input.mediaAssetId); await assertPublicMedia(db, ctx.user.id, input.socialPreviewMediaAssetId); const [row] = await db.insert(announcements).values({ subjectId: input.subjectId, publicId: nanoid(12), title: input.title, body: input.body, mediaAssetId: input.mediaAssetId ?? null, socialPreviewMediaAssetId: input.socialPreviewMediaAssetId ?? null }).$returningId(); return { id: row.id }; }),
    update: ownerProcedure.input(z.object({ id: z.number().int().positive(), title: z.string().trim().min(2).max(220), body: z.string().trim().min(1).max(20000), mediaAssetId: publicMediaInput, socialPreviewMediaAssetId: publicMediaInput, summary: updateSummary })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: announcements.id, version: announcements.version }).from(announcements).innerJoin(subjects, eq(announcements.subjectId, subjects.id)).where(and(eq(announcements.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Announcement not found"); await assertPublicMedia(db, ctx.user.id, input.mediaAssetId); await assertPublicMedia(db, ctx.user.id, input.socialPreviewMediaAssetId); const version = row[0].version + 1; await db.update(announcements).set({ title: input.title, body: input.body, mediaAssetId: input.mediaAssetId ?? null, socialPreviewMediaAssetId: input.socialPreviewMediaAssetId ?? null, publishState: "published", version, publicChangeSummary: input.summary, publishedAt: new Date() }).where(eq(announcements.id, input.id)); await db.insert(historyEntries).values({ entityType: "announcement", entityId: input.id, version, action: "updated", publicChangeSummary: input.summary, actorUserId: ctx.user.id }); return { version }; }),
    publish: ownerProcedure.input(z.object({ id: z.number().int().positive(), summary: updateSummary })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: announcements.id, version: announcements.version }).from(announcements).innerJoin(subjects, eq(announcements.subjectId, subjects.id)).where(and(eq(announcements.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Announcement not found"); const version = row[0].version + 1; await db.update(announcements).set({ publishState: "published", version, publicChangeSummary: input.summary, publishedAt: new Date() }).where(eq(announcements.id, input.id)); await db.insert(historyEntries).values({ entityType: "announcement", entityId: input.id, version, action: "published", publicChangeSummary: input.summary, actorUserId: ctx.user.id }); return { version }; }),
    archive: ownerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: announcements.id }).from(announcements).innerJoin(subjects, eq(announcements.subjectId, subjects.id)).where(and(eq(announcements.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Announcement not found"); await db.update(announcements).set({ publishState: "archived" }).where(eq(announcements.id, input.id)); return { success: true as const }; }),
    restore: ownerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: announcements.id }).from(announcements).innerJoin(subjects, eq(announcements.subjectId, subjects.id)).where(and(eq(announcements.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Announcement not found"); await db.update(announcements).set({ publishState: "draft" }).where(eq(announcements.id, input.id)); return { success: true as const }; }),
  }),
  resources: router({
    list: ownerProcedure.input(subjectInput).query(async ({ ctx, input }) => (await assertSubject(ctx.user.id, input.subjectId)).select().from(resources).where(eq(resources.subjectId, input.subjectId)).orderBy(desc(resources.updatedAt))),
    create: ownerProcedure.input(subjectInput.extend({ title: z.string().trim().min(2).max(220), description: z.string().trim().min(1).max(5000), category: z.string().trim().min(2).max(80), resourceType: z.string().trim().min(2).max(80), destinationUrl: z.string().url().max(4000), fallbackMediaAssetId: publicMediaInput, socialPreviewMediaAssetId: publicMediaInput })).mutation(async ({ ctx, input }) => { const db = await assertSubject(ctx.user.id, input.subjectId); await assertPublicMedia(db, ctx.user.id, input.fallbackMediaAssetId); await assertPublicMedia(db, ctx.user.id, input.socialPreviewMediaAssetId); const sourceDomain = new URL(input.destinationUrl).hostname; const [row] = await db.insert(resources).values({ subjectId: input.subjectId, publicId: nanoid(12), title: input.title, description: input.description, category: input.category, resourceType: input.resourceType, sourceDomain, destinationUrl: input.destinationUrl, fallbackMediaAssetId: input.fallbackMediaAssetId ?? null, socialPreviewMediaAssetId: input.socialPreviewMediaAssetId ?? null }).$returningId(); return { id: row.id }; }),
    update: ownerProcedure.input(z.object({ id: z.number().int().positive(), title: z.string().trim().min(2).max(220), description: z.string().trim().min(1).max(5000), category: z.string().trim().min(2).max(80), resourceType: z.string().trim().min(2).max(80), destinationUrl: z.string().url().max(4000), fallbackMediaAssetId: publicMediaInput, socialPreviewMediaAssetId: publicMediaInput, summary: updateSummary })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: resources.id, version: resources.version }).from(resources).innerJoin(subjects, eq(resources.subjectId, subjects.id)).where(and(eq(resources.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Resource not found"); await assertPublicMedia(db, ctx.user.id, input.fallbackMediaAssetId); await assertPublicMedia(db, ctx.user.id, input.socialPreviewMediaAssetId); const version = row[0].version + 1; await db.update(resources).set({ title: input.title, description: input.description, category: input.category, resourceType: input.resourceType, destinationUrl: input.destinationUrl, sourceDomain: new URL(input.destinationUrl).hostname, fallbackMediaAssetId: input.fallbackMediaAssetId ?? null, socialPreviewMediaAssetId: input.socialPreviewMediaAssetId ?? null, publishState: "published", version, publicChangeSummary: input.summary, publishedAt: new Date() }).where(eq(resources.id, input.id)); await db.insert(historyEntries).values({ entityType: "resource", entityId: input.id, version, action: "updated", publicChangeSummary: input.summary, actorUserId: ctx.user.id }); return { version }; }),
    publish: ownerProcedure.input(z.object({ id: z.number().int().positive(), summary: updateSummary })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: resources.id, version: resources.version }).from(resources).innerJoin(subjects, eq(resources.subjectId, subjects.id)).where(and(eq(resources.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Resource not found"); const version = row[0].version + 1; await db.update(resources).set({ publishState: "published", version, publicChangeSummary: input.summary, publishedAt: new Date() }).where(eq(resources.id, input.id)); await db.insert(historyEntries).values({ entityType: "resource", entityId: input.id, version, action: "published", publicChangeSummary: input.summary, actorUserId: ctx.user.id }); return { version }; }),
    archive: ownerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: resources.id }).from(resources).innerJoin(subjects, eq(resources.subjectId, subjects.id)).where(and(eq(resources.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Resource not found"); await db.update(resources).set({ publishState: "archived" }).where(eq(resources.id, input.id)); return { success: true as const }; }),
    restore: ownerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: resources.id }).from(resources).innerJoin(subjects, eq(resources.subjectId, subjects.id)).where(and(eq(resources.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Resource not found"); await db.update(resources).set({ publishState: "draft" }).where(eq(resources.id, input.id)); return { success: true as const }; }),
  }),
  questions: router({
    list: ownerProcedure.input(subjectInput).query(async ({ ctx, input }) => (await assertSubject(ctx.user.id, input.subjectId)).select().from(questionsAnswers).where(eq(questionsAnswers.subjectId, input.subjectId)).orderBy(desc(questionsAnswers.updatedAt))),
    create: ownerProcedure.input(subjectInput.extend({ question: z.string().trim().min(3).max(5000), answer: z.string().trim().min(1).max(10000), tagsText: z.string().max(1000).nullable().optional(), isOfficial: z.boolean().default(false), socialPreviewMediaAssetId: publicMediaInput })).mutation(async ({ ctx, input }) => { const db = await assertSubject(ctx.user.id, input.subjectId); await assertPublicMedia(db, ctx.user.id, input.socialPreviewMediaAssetId); const [row] = await db.insert(questionsAnswers).values({ subjectId: input.subjectId, publicId: nanoid(12), question: input.question, answer: input.answer, tagsText: input.tagsText ?? null, isOfficial: input.isOfficial, socialPreviewMediaAssetId: input.socialPreviewMediaAssetId ?? null }).$returningId(); return { id: row.id }; }),
    update: ownerProcedure.input(z.object({ id: z.number().int().positive(), question: z.string().trim().min(3).max(5000), answer: z.string().trim().min(1).max(10000), tagsText: z.string().max(1000).nullable().optional(), isOfficial: z.boolean(), socialPreviewMediaAssetId: publicMediaInput, summary: updateSummary })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: questionsAnswers.id, version: questionsAnswers.version }).from(questionsAnswers).innerJoin(subjects, eq(questionsAnswers.subjectId, subjects.id)).where(and(eq(questionsAnswers.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Question & Answer not found"); await assertPublicMedia(db, ctx.user.id, input.socialPreviewMediaAssetId); const version = row[0].version + 1; await db.update(questionsAnswers).set({ question: input.question, answer: input.answer, tagsText: input.tagsText ?? null, isOfficial: input.isOfficial, socialPreviewMediaAssetId: input.socialPreviewMediaAssetId ?? null, publishState: "published", version, publicChangeSummary: input.summary, publishedAt: new Date() }).where(eq(questionsAnswers.id, input.id)); await db.insert(historyEntries).values({ entityType: "question", entityId: input.id, version, action: "updated", publicChangeSummary: input.summary, actorUserId: ctx.user.id }); return { version }; }),
    publish: ownerProcedure.input(z.object({ id: z.number().int().positive(), summary: updateSummary, official: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: questionsAnswers.id, version: questionsAnswers.version }).from(questionsAnswers).innerJoin(subjects, eq(questionsAnswers.subjectId, subjects.id)).where(and(eq(questionsAnswers.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Question & Answer not found"); const version = row[0].version + 1; await db.update(questionsAnswers).set({ publishState: "published", version, isOfficial: input.official, publicChangeSummary: input.summary, publishedAt: new Date() }).where(eq(questionsAnswers.id, input.id)); await db.insert(historyEntries).values({ entityType: "question", entityId: input.id, version, action: "published", publicChangeSummary: input.summary, actorUserId: ctx.user.id }); return { version }; }),
    archive: ownerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: questionsAnswers.id }).from(questionsAnswers).innerJoin(subjects, eq(questionsAnswers.subjectId, subjects.id)).where(and(eq(questionsAnswers.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Question & Answer not found"); await db.update(questionsAnswers).set({ publishState: "archived" }).where(eq(questionsAnswers.id, input.id)); return { success: true as const }; }),
    restore: ownerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await databaseOrThrow(); const row = await db.select({ id: questionsAnswers.id }).from(questionsAnswers).innerJoin(subjects, eq(questionsAnswers.subjectId, subjects.id)).where(and(eq(questionsAnswers.id, input.id), eq(subjects.ownerId, ctx.user.id))).limit(1); if (!row[0]) throw new Error("Question & Answer not found"); await db.update(questionsAnswers).set({ publishState: "draft" }).where(eq(questionsAnswers.id, input.id)); return { success: true as const }; }),
  }),
});
