import DashboardLayout from "@/components/DashboardLayout";
import { WorkspacePageHeader } from "@/components/WorkspacePageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, CalendarDays, CalendarX, Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { Link, useRoute } from "wouter";

const weekdayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
type Composer = "session" | "no-class" | null;

export function FocusedSchedulePage() {
  const [, params] = useRoute("/app/subjects/:subjectId/schedule");
  const subjectId = Number(params?.subjectId);
  const subject = trpc.subjects.get.useQuery({ subjectId }, { enabled: Number.isFinite(subjectId) && subjectId > 0 });
  const sessions = trpc.subjects.sessions.list.useQuery({ subjectId }, { enabled: Number.isFinite(subjectId) && subjectId > 0 });
  const utils = trpc.useUtils();
  const [composer, setComposer] = useState<Composer>(null);
  const [sessionAt, setSessionAt] = useState("");
  const [noClassAt, setNoClassAt] = useState("");
  const [reason, setReason] = useState("");
  const [sessionForNoClass, setSessionForNoClass] = useState<number | null>(null);
  const refresh = () => utils.subjects.sessions.list.invalidate({ subjectId });
  const createSession = trpc.subjects.sessions.create.useMutation({ onSuccess: () => { refresh(); setSessionAt(""); setComposer(null); toast.success("Class session added"); }, onError: error => toast.error(error.message) });
  const createNoClass = trpc.subjects.sessions.createNoClass.useMutation({ onSuccess: () => { refresh(); setNoClassAt(""); setReason(""); setComposer(null); toast.success("No Class notice added"); }, onError: error => toast.error(error.message) });
  const setNoClass = trpc.subjects.sessions.setNoClass.useMutation({ onSuccess: () => { refresh(); setReason(""); setSessionForNoClass(null); toast.success("Class session updated"); }, onError: error => toast.error(error.message) });
  const fixedSchedule = subject.data?.meetingDays.map(day => `${weekdayNames[day.weekday]}${day.startTime ? ` · ${day.startTime}${day.endTime ? `–${day.endTime}` : ""}` : ""}`).join(" · ") || "No fixed weekday schedule";
  const closeComposer = () => { setComposer(null); setSessionAt(""); setNoClassAt(""); setReason(""); };
  const submitSession = (event: FormEvent) => { event.preventDefault(); if (sessionAt) createSession.mutate({ subjectId, startsAt: new Date(sessionAt) }); };
  const submitNoClass = (event: FormEvent) => { event.preventDefault(); if (noClassAt && reason.trim()) createNoClass.mutate({ subjectId, startsAt: new Date(noClassAt), reason: reason.trim() }); };

  if (!subject.data && !subject.isLoading) return <DashboardLayout><section className="mx-auto grid min-h-[55vh] max-w-2xl place-items-center"><div className="rounded-[30px] bg-secondary/35 p-1 ring-1 ring-border/75"><div className="rounded-[26px] bg-card p-8 text-center"><CalendarDays className="mx-auto text-muted-foreground" /><h1 className="mt-4 text-xl font-semibold">Subject unavailable</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">This private class record may have been removed or is not available in the current workspace.</p><Link href="/app/subjects" className="mt-6 inline-flex min-h-11 items-center rounded-2xl bg-primary px-4 text-sm font-semibold text-primary-foreground">Back to Subjects</Link></div></div></section></DashboardLayout>;

  return <DashboardLayout><section className="mx-auto max-w-4xl"><WorkspacePageHeader eyebrow="Class schedule" title="Schedule & No Class" description="Keep the calendar focused on one Subject. Use a separate short form when a new session or No Class notice needs to be added." back={<Link href={`/app/subjects/${subjectId}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl text-sm font-medium text-muted-foreground hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ArrowLeft />Back to Subject</Link>} action={<div className="flex gap-2"><Button variant="outline" onClick={() => setComposer("no-class")} className="min-h-11 rounded-2xl"><CalendarX data-icon="inline-start" />No Class</Button><Button onClick={() => setComposer("session")} className="min-h-11 rounded-2xl"><Plus data-icon="inline-start" />New session</Button></div>} />
    {subject.data ? <div className="mt-7 flex flex-col gap-6"><section className="rounded-[30px] bg-secondary/35 p-1 ring-1 ring-border/75"><div className="rounded-[26px] bg-card p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.06)] sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Fixed weekly schedule</p><p className="mt-2 text-xl font-semibold tracking-[-0.025em]">{fixedSchedule}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Change the repeating weekday schedule from Subject details. Session dates below are managed separately so exceptions remain easy to scan.</p><Link href={`/app/subjects/${subjectId}/details`} className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-primary">Edit fixed schedule <ArrowRight data-icon="inline-end" /></Link></div></section>
      <section className="rounded-[30px] bg-secondary/35 p-1 ring-1 ring-border/75"><div className="rounded-[26px] bg-card p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.06)] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Session timeline</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.035em]">Upcoming and retained class dates.</h2></div><Badge variant="secondary" className="rounded-full px-3 py-1">{sessions.data?.length ?? 0} total</Badge></div><div className="mt-6 flex flex-col gap-3">{sessions.isLoading ? <p className="py-10 text-center text-sm text-muted-foreground">Loading sessions…</p> : null}{sessions.data?.map(session => <article key={session.id} className="flex flex-col gap-4 rounded-2xl bg-secondary/60 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{new Date(session.startsAt).toLocaleString()}</p><p className="mt-1 text-sm text-muted-foreground">{session.sessionState === "no_class" ? `No Class · ${session.noClassReason}` : session.sessionState === "completed" ? "Class session · Attendance completed" : "Scheduled class session"}</p></div><div className="flex flex-wrap gap-2">{session.sessionState === "no_class" ? <Button type="button" variant="outline" disabled={setNoClass.isPending} onClick={() => setNoClass.mutate({ sessionId: session.id, noClass: false, publish: true })} className="min-h-11 rounded-xl">Restore class</Button> : <><Link href={`/app/attendance/${session.id}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-3 text-sm font-semibold text-primary-foreground">Attendance <ArrowRight data-icon="inline-end" /></Link><Button type="button" variant="outline" onClick={() => { setSessionForNoClass(session.id); setReason(""); }} className="min-h-11 rounded-xl">Set No Class</Button></>}</div></article>)}{!sessions.isLoading && !sessions.data?.length ? <div className="py-12 text-center"><CalendarDays className="mx-auto text-muted-foreground" /><p className="mt-4 font-semibold">No individual sessions yet</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Add the next class session, or publish a direct No Class date for an exception.</p><Button onClick={() => setComposer("session")} className="mt-5 min-h-11 rounded-2xl">Add class session</Button></div> : null}</div></div></section></div> : <div className="mt-7 grid min-h-72 place-items-center rounded-[30px] border border-border bg-card text-sm text-muted-foreground">Loading Subject workspace…</div>}
    <Dialog open={composer !== null} onOpenChange={open => !open && closeComposer()}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{composer === "session" ? "New class session" : "New No Class notice"}</DialogTitle><DialogDescription>{composer === "session" ? "Create one class date for this Subject. Attendance stays in its own focused workflow." : "Create a direct notice for a holiday, event, weather day, or other schedule exception."}</DialogDescription></DialogHeader>{composer === "session" ? <form onSubmit={submitSession} className="mt-4 flex flex-col gap-3"><Label htmlFor="new-session-date">Class date and time</Label><Input id="new-session-date" type="datetime-local" required value={sessionAt} onChange={event => setSessionAt(event.target.value)} /><DialogFooter className="mt-2"><Button type="button" variant="outline" onClick={closeComposer} className="min-h-11 rounded-2xl">Cancel</Button><Button disabled={createSession.isPending || !sessionAt} className="min-h-11 rounded-2xl">{createSession.isPending ? "Adding…" : "Add session"}</Button></DialogFooter></form> : <form onSubmit={submitNoClass} className="mt-4 flex flex-col gap-3"><Label htmlFor="no-class-date">No Class date and time</Label><Input id="no-class-date" type="datetime-local" required value={noClassAt} onChange={event => setNoClassAt(event.target.value)} /><Label htmlFor="no-class-reason">Reason</Label><Input id="no-class-reason" required value={reason} onChange={event => setReason(event.target.value)} placeholder="Holiday, school event, weather, or other" /><DialogFooter className="mt-2"><Button type="button" variant="outline" onClick={closeComposer} className="min-h-11 rounded-2xl">Cancel</Button><Button disabled={createNoClass.isPending || !noClassAt || !reason.trim()} className="min-h-11 rounded-2xl">{createNoClass.isPending ? "Adding…" : "Add No Class notice"}</Button></DialogFooter></form>}</DialogContent></Dialog>
    <Dialog open={sessionForNoClass !== null} onOpenChange={open => !open && setSessionForNoClass(null)}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Set No Class</DialogTitle><DialogDescription>Replace this scheduled session with a direct No Class notice. You can restore the class later.</DialogDescription></DialogHeader><div className="mt-4 flex flex-col gap-3"><Label htmlFor="session-no-class-reason">Reason</Label><Input id="session-no-class-reason" value={reason} onChange={event => setReason(event.target.value)} placeholder="Holiday, event, weather, or other" /><DialogFooter className="mt-2"><Button type="button" variant="outline" onClick={() => setSessionForNoClass(null)} className="min-h-11 rounded-2xl">Cancel</Button><Button disabled={setNoClass.isPending || !reason.trim()} onClick={() => sessionForNoClass && setNoClass.mutate({ sessionId: sessionForNoClass, noClass: true, reason: reason.trim(), publish: true })} className="min-h-11 rounded-2xl">Set No Class</Button></DialogFooter></div></DialogContent></Dialog>
  </section></DashboardLayout>;
}
