import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BellRing, BookOpen, CalendarDays, CircleAlert, ClipboardCheck, ExternalLink, MessageCircleMore } from "lucide-react";
import { useMemo } from "react";
import { Link, useRoute } from "wouter";

const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export function PremiumPublicSubjectHome() {
  const [, params] = useRoute("/s/:publicId"); const input = useMemo(() => ({ publicId: params?.publicId ?? "" }), [params?.publicId]); const query = trpc.foundation.publicSubject.useQuery(input, { enabled: Boolean(input.publicId) });
  if (query.isLoading) return <PublicFrame><div className="signal-panel p-6 text-sm text-muted-foreground">Loading Subject…</div></PublicFrame>;
  if (!query.data?.available) return <PublicFrame><div className="signal-panel border-t-2 border-primary p-7 text-center"><CircleAlert className="mx-auto size-6 text-primary" /><h1 className="signal-heading mt-4">Subject unavailable</h1><p className="mt-2 text-sm text-muted-foreground">This link is not shared.</p></div></PublicFrame>;
  const { latest, ...subject } = query.data.subject; const schedule = subject.meetingDays.length ? subject.meetingDays.map(day => `${dayNames[day.weekday]}${day.startTime ? ` · ${day.startTime}${day.endTime ? `–${day.endTime}` : ""}` : ""}`).join(" · ") : "Schedule pending";
  return <PublicFrame><article className="signal-panel border-t-2 border-primary p-5 sm:p-7"><div className="grid gap-7 lg:grid-cols-[minmax(0,1.35fr)_minmax(15rem,.65fr)] lg:items-end"><div><Badge className="rounded-full bg-primary px-2.5 py-0.5 text-primary-foreground">{subject.code}</Badge><h1 className="signal-title mt-5 max-w-2xl">{subject.name}</h1><p className="mt-3 text-sm font-semibold text-foreground/85">Professor {subject.professorName}</p></div><section className="signal-inset border-l-2 border-l-primary p-4"><div className="flex items-center gap-2 text-primary"><CalendarDays className="size-4" /><p className="signal-kicker">Schedule</p></div><p className="mt-3 text-sm leading-6 text-foreground/90">{schedule}</p></section></div></article>{subject.noClass ? <section className="mt-4 border-l-2 border-amber-300 bg-amber-300/10 p-4"><div className="flex gap-3"><CircleAlert className="mt-0.5 size-5 shrink-0 text-amber-300" /><div><p className="font-semibold">No Class · {new Date(subject.noClass.startsAt).toLocaleDateString()}</p><p className="mt-1 text-sm text-muted-foreground">{subject.noClass.reason}</p></div></div></section> : null}<section className="mt-6 grid gap-4 lg:grid-cols-[minmax(0,1.2fr)_minmax(16rem,.8fr)]"><RecordList icon={ClipboardCheck} eyebrow="Attendance" title="Class Attendance" items={latest.attendance.map(item => ({ ...item, title: new Date(item.startsAt).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) }))} hrefPrefix="/attendance/" empty="No Attendance published." /><RecordList icon={MessageCircleMore} eyebrow="Answers" title="Questions & Answers" items={latest.questions} hrefPrefix="/q/" empty="No answers published." allHref={`/s/${subject.publicId}/questions`} /></section><section className="mt-4 grid gap-4 sm:grid-cols-2"><RecordList icon={BellRing} eyebrow="Updates" title="Announcements" items={latest.announcements} hrefPrefix="/a/" empty="No announcements published." /><section className="signal-panel p-5 sm:p-6"><div className="flex items-center gap-2"><BookOpen className="size-4 text-primary" /><p className="signal-kicker">Resources</p></div>{latest.resources.length ? <div className="mt-4 divide-y divide-border">{latest.resources.slice(0, 3).map(item => <Link key={item.publicId} href={`/r/${item.publicId}`} className="signal-action group flex min-h-14 items-center justify-between gap-3 px-3 hover:bg-secondary"><span className="min-w-0 truncate text-sm font-semibold">{item.title}</span><ExternalLink className="size-4 shrink-0 text-primary" /></Link>)}</div> : <EmptySurface label="No resources published." />}</section></section></PublicFrame>;
}

function RecordList({ icon: Icon, eyebrow, title, items, hrefPrefix, empty, allHref }: { icon: typeof BellRing; eyebrow: string; title: string; items: Array<{ publicId: string; title: string }>; hrefPrefix: string; empty: string; allHref?: string }) { return <section className="signal-panel p-5 sm:p-6"><div className="flex items-center gap-2"><Icon className="size-4 text-primary" /><p className="signal-kicker">{eyebrow}</p></div><h2 className="signal-heading mt-3">{title}</h2>{items.length ? <div className="mt-4 divide-y divide-border">{items.slice(0, 3).map(item => <Link key={item.publicId} href={`${hrefPrefix}${item.publicId}`} className="signal-action group flex min-h-14 items-center justify-between gap-3 px-3 hover:bg-secondary"><span className="min-w-0 truncate text-sm font-semibold">{item.title}</span><ArrowRight className="size-4 shrink-0 text-primary transition-transform group-hover:translate-x-0.5" /></Link>)}</div> : <EmptySurface label={empty} />}{allHref && items.length ? <Link href={allHref} className="signal-action mt-3 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-primary">All answers <ArrowRight className="size-4" /></Link> : null}</section>; }
function EmptySurface({ label }: { label: string }) { return <div className="signal-inset mt-4 px-4 py-4 text-sm text-muted-foreground">{label}</div>; }
function PublicFrame({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-background px-5 py-5 text-foreground sm:px-8 sm:py-9"><div className="mx-auto max-w-5xl"><header className="mb-8 flex min-h-14 items-center justify-between gap-4 border-b border-border pb-4"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold tracking-[-0.03em] text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="grid size-9 place-items-center rounded-xl bg-primary text-xs font-extrabold text-primary-foreground">CM</span><span>Class Management</span></Link><span className="rounded-full border border-primary/30 bg-primary/10 px-2.5 py-1 text-[11px] font-semibold tracking-wide text-primary">VIEW ONLY</span></header><div className="pb-8">{children}</div><footer className="border-t border-border pt-5 text-center text-xs text-muted-foreground">View-only class information</footer></div></main>; }
