import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BellRing, BookOpen, CalendarDays, CircleAlert, ClipboardCheck, ExternalLink, GraduationCap, MessageCircleMore, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useMemo } from "react";

const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export function PremiumPublicSubjectHome() {
  const [, params] = useRoute("/s/:publicId");
  const input = useMemo(() => ({ publicId: params?.publicId ?? "" }), [params?.publicId]);
  const query = trpc.foundation.publicSubject.useQuery(input, { enabled: Boolean(input.publicId) });
  if (query.isLoading) return <PublicFrame><div className="rounded-[28px] border border-border bg-card p-7 text-sm text-muted-foreground">Loading shared Subject…</div></PublicFrame>;
  if (!query.data?.available) return <PublicFrame><div className="rounded-[28px] border border-border bg-card p-7 text-center"><CircleAlert className="mx-auto size-6 text-muted-foreground" /><h1 className="mt-4 text-xl font-semibold">This shared Subject is not available</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">The link may be incomplete, unpublished, or no longer shared.</p></div></PublicFrame>;
  const { latest, ...subject } = query.data.subject;
  const schedule = subject.meetingDays.length ? subject.meetingDays.map(day => `${dayNames[day.weekday]}${day.startTime ? ` · ${day.startTime}${day.endTime ? `–${day.endTime}` : ""}` : ""}`).join("  ·  ") : "Schedule will be shared soon.";
  return <PublicFrame>
    <article className="apple-surface rounded-[30px] p-6 sm:p-8"><div className="grid gap-7 lg:grid-cols-[minmax(0,1.35fr)_minmax(15rem,.65fr)] lg:items-end"><div><div className="flex flex-wrap items-center gap-2"><Badge className="rounded-full bg-primary px-3 py-1 text-primary-foreground">{subject.code}</Badge><Badge variant="outline" className="rounded-full border-primary/30 bg-primary/5 px-3 py-1 text-primary">Shared Subject</Badge></div><h1 className="apple-title mt-5 max-w-2xl sm:text-5xl">{subject.name}</h1><p className="mt-5 text-sm font-medium text-foreground/85">Professor {subject.professorName}</p><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">A view-only class space for the latest official updates, attendance, resources, and reusable answers.</p></div><section className="apple-inset rounded-[18px] p-4"><div className="flex items-center gap-2 text-primary"><CalendarDays className="size-4" /><p className="text-xs font-semibold uppercase tracking-[0.12em]">Class schedule</p></div><p className="mt-3 text-sm leading-6 text-foreground/90">{schedule}</p></section></div></article>
    {subject.noClass ? <section className="mt-4 rounded-[24px] border border-amber-400/30 bg-amber-400/10 p-5"><div className="flex gap-3"><CircleAlert className="mt-0.5 size-5 shrink-0 text-amber-300" /><div><p className="font-semibold">No Class · {new Date(subject.noClass.startsAt).toLocaleDateString()}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{subject.noClass.reason}</p></div></div></section> : null}
    <section className="mt-6 grid gap-4 lg:grid-cols-[minmax(0,1.2fr)_minmax(16rem,.8fr)]"><section className="rounded-[28px] border border-border bg-card p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ClipboardCheck className="size-5 text-primary" /><p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">Class record</p></div><h2 className="mt-3 text-2xl font-semibold tracking-[-0.035em]">Published Attendance</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Review the final class-session records shared by the secretary.</p></div><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><Sparkles className="size-5" /></span></div>{latest.attendance.length ? <div className="mt-5 space-y-2">{latest.attendance.slice(0, 3).map(item => <Link key={item.publicId} href={`/attendance/${item.publicId}`} className="group flex min-h-14 items-center justify-between gap-3 rounded-2xl border border-border bg-secondary/55 px-4 text-sm font-semibold transition-colors hover:border-primary/50 hover:bg-primary/5"><span>{new Date(item.startsAt).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}</span><ArrowRight className="size-4 text-primary transition-transform group-hover:translate-x-0.5" /></Link>)}</div> : <EmptySurface label="Published class-session Attendance will appear here." />}</section>
      <section className="rounded-[28px] border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-2"><MessageCircleMore className="size-5 text-primary" /><p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">Quick help</p></div><h2 className="mt-3 text-2xl font-semibold tracking-[-0.035em]">Questions & Answers</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Official answers collected from recurring Messenger questions.</p>{latest.questions.length ? <div className="mt-5 space-y-2">{latest.questions.slice(0, 2).map(item => <Link key={item.publicId} href={`/q/${item.publicId}`} className="group block rounded-2xl border border-border bg-secondary/55 p-3 transition-colors hover:border-primary/50 hover:bg-primary/5"><p className="line-clamp-2 text-sm font-semibold">{item.title}</p><span className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-primary">Read answer <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-0.5" /></span></Link>)}</div> : <EmptySurface label="Shared answers will appear here." />}{latest.questions.length ? <Link href={`/s/${subject.publicId}/questions`} className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-primary hover:text-primary/80">Browse all answers <ArrowRight className="size-4" /></Link> : null}</section></section>
    <section className="mt-4 grid gap-4 sm:grid-cols-2"><HomeList icon={BellRing} eyebrow="Official updates" title="Announcements" items={latest.announcements} hrefPrefix="/a/" empty="No published announcements yet." /><section className="rounded-[28px] border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-2"><BookOpen className="size-5 text-primary" /><p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">Class library</p></div><h2 className="mt-3 text-2xl font-semibold tracking-[-0.035em]">Resources</h2>{latest.resources.length ? <div className="mt-5 grid gap-2">{latest.resources.slice(0, 3).map(item => <Link key={item.publicId} href={`/r/${item.publicId}`} className="group flex min-h-14 items-center justify-between gap-3 rounded-2xl border border-border bg-secondary/55 px-4 transition-colors hover:border-primary/50 hover:bg-primary/5"><span className="min-w-0"><span className="block truncate text-sm font-semibold">{item.title}</span><span className="mt-1 block text-xs text-muted-foreground">Open shared resource</span></span><ExternalLink className="size-4 shrink-0 text-primary" /></Link>)}</div> : <EmptySurface label="Class links and materials will appear here." />}</section></section>
  </PublicFrame>;
}

function HomeList({ icon: Icon, eyebrow, title, items, hrefPrefix, empty }: { icon: typeof BellRing; eyebrow: string; title: string; items: Array<{ publicId: string; title: string }>; hrefPrefix: string; empty: string }) { return <section className="rounded-[28px] border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-2"><Icon className="size-5 text-primary" /><p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">{eyebrow}</p></div><h2 className="mt-3 text-2xl font-semibold tracking-[-0.035em]">{title}</h2>{items.length ? <div className="mt-5 space-y-2">{items.slice(0, 3).map(item => <Link key={item.publicId} href={`${hrefPrefix}${item.publicId}`} className="group flex min-h-14 items-center justify-between gap-3 rounded-2xl border border-border bg-secondary/55 px-4 transition-colors hover:border-primary/50 hover:bg-primary/5"><span className="min-w-0 truncate text-sm font-semibold">{item.title}</span><ArrowRight className="size-4 shrink-0 text-primary transition-transform group-hover:translate-x-0.5" /></Link>)}</div> : <EmptySurface label={empty} />}</section>; }
function EmptySurface({ label }: { label: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-border bg-secondary/35 px-4 py-5 text-sm leading-6 text-muted-foreground">{label}</div>; }
function PublicFrame({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-background px-5 py-5 text-foreground sm:px-8 sm:py-9"><div className="mx-auto max-w-5xl"><header className="apple-material mb-7 flex min-h-14 items-center justify-between gap-4 rounded-[18px] border border-border/70 px-3 py-2"><Link href="/" className="inline-flex items-center gap-2 rounded-xl text-sm font-semibold tracking-[-0.03em] text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="grid size-9 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">CM</span><span>Class Management</span></Link><span className="rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 text-[11px] font-semibold tracking-wide text-primary">VIEW ONLY</span></header><div className="pb-8">{children}</div><footer className="border-t border-border/70 pt-5 text-center text-xs leading-5 text-muted-foreground">Shared class information · View only · Managed by the class secretary</footer></div></main>; }
