import { BookOpen, CalendarDays, CircleAlert, CircleHelp, ExternalLink, History, MessageCircleMore, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { AnnouncementPreview } from "@/components/AnnouncementPreview";

const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export function PublicSubjectPage() {
  const [, params] = useRoute("/s/:publicId");
  const input = useMemo(() => ({ publicId: params?.publicId ?? "" }), [params?.publicId]);
  const subject = trpc.foundation.publicSubject.useQuery(input, { enabled: Boolean(input.publicId) });
  if (subject.isLoading) return <PublicShell><p className="text-sm text-muted-foreground">Loading Subject…</p></PublicShell>;
  if (!subject.data?.available) return <PublicUnavailable />;
  const details = subject.data.subject;
  return <PublicShell><p className="text-sm font-semibold text-primary">{details.code}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.035em]">{details.name}</h1><p className="mt-2 text-sm text-muted-foreground">Professor {details.professorName}</p><section className="mt-7 rounded-[28px] border border-border bg-card p-5"><div className="flex gap-3"><CalendarDays className="mt-0.5 h-5 w-5 text-primary" /><div><h2 className="font-semibold">Schedule</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{details.meetingDays.length ? details.meetingDays.map(day => `${dayNames[day.weekday]}${day.startTime ? ` · ${day.startTime}${day.endTime ? `–${day.endTime}` : ""}` : ""}`).join(" · ") : "Schedule will be shared soon."}</p></div></div></section>{details.noClass ? <section className="mt-4 rounded-[24px] border border-amber-400/30 bg-amber-400/10 p-5"><div className="flex gap-3"><CircleAlert className="mt-0.5 h-5 w-5 text-amber-300" /><div><h2 className="font-semibold">No Class</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{new Date(details.noClass.startsAt).toLocaleDateString()} — {details.noClass.reason}</p></div></div></section> : null}<section className="mt-7 grid gap-3 sm:grid-cols-2"><PublicAttendanceList items={details.latest.attendance} /><PublicList icon={MessageCircleMore} title="Questions & Answers" items={details.latest.questions} pathPrefix="/q/" empty="Shared answers will appear here." allHref={`/s/${details.publicId}/questions`} /><PublicList icon={ExternalLink} title="Announcements" items={details.latest.announcements} pathPrefix="/a/" empty="Official updates will appear here." /><PublicResourceCards items={details.latest.resources} /></section></PublicShell>;
}

export function PublicSubjectQuestionsPage() {
  const [, params] = useRoute("/s/:publicId/questions");
  const publicId = params?.publicId ?? "";
  const [searchDraft, setSearchDraft] = useState("");
  const [search, setSearch] = useState("");
  const questions = trpc.foundation.publicQuestions.useQuery({ publicId, query: search || undefined }, { enabled: Boolean(publicId) });
  if (questions.isLoading) return <PublicShell><p className="text-sm text-muted-foreground">Loading Questions & Answers…</p></PublicShell>;
  if (!questions.data?.available) return <PublicUnavailable />;
  const { subject, questions: items } = questions.data;
  return <PublicShell><Link href={`/s/${subject.publicId}`} className="text-sm font-semibold text-primary">{subject.code} · {subject.name}</Link><div className="mt-5"><p className="text-sm font-semibold text-primary">Shared answers</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Questions & Answers</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Browse published answers or search by topic, question, answer, or tag.</p></div><form className="mt-5 flex gap-2" onSubmit={event => { event.preventDefault(); setSearch(searchDraft.trim()); }}><input type="search" value={searchDraft} onChange={event => setSearchDraft(event.target.value)} className="min-h-11 flex-1 rounded-2xl border border-input bg-card px-3 text-sm text-foreground" placeholder="Search published answers" aria-label="Search published answers" /><button type="submit" className="min-h-11 rounded-2xl bg-primary px-4 text-sm font-semibold text-primary-foreground">Search</button></form>{search ? <p className="mt-3 text-sm text-muted-foreground">{items.length} {items.length === 1 ? "answer" : "answers"} for “{search}”</p> : null}<section className="mt-5 space-y-3">{items.map(item => { const tags = item.tagsText?.split(",").map(tag => tag.trim()).filter(Boolean) ?? []; return <Link key={item.publicId} href={`/q/${item.publicId}`} className="block rounded-[24px] border border-border bg-card p-5 hover:border-primary/60"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className={`rounded-full text-xs ${item.isOfficial ? "border-emerald-400/30 text-emerald-200" : "border-amber-400/30 text-amber-200"}`}>{item.isOfficial ? "Official answer" : "Unofficial answer"}</Badge>{tags.map(tag => <Badge key={tag} variant="outline" className="rounded-full text-xs">{tag}</Badge>)}</div><h2 className="mt-3 text-lg font-semibold">{item.question}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-muted-foreground">{item.answer}</p>{item.publishedAt ? <p className="mt-3 text-xs text-muted-foreground">Published {new Date(item.publishedAt).toLocaleDateString()}</p> : null}</Link>; })}{!items.length ? <div className="rounded-[24px] border border-border bg-card p-6 text-center"><h2 className="font-semibold">No published answers found</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Try another topic or return to the Subject Home.</p></div> : null}</section></PublicShell>;
}

export function PublicUnavailable() { return <PublicShell><section className="rounded-[28px] border border-border bg-card p-7 text-center"><CircleAlert className="mx-auto h-6 w-6 text-muted-foreground" /><h1 className="mt-4 text-xl font-semibold">This page is not available</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">The link may be incomplete, unpublished, or no longer shared.</p><Link href="/" className="mt-6 inline-flex min-h-11 items-center rounded-2xl bg-primary px-4 text-sm font-semibold text-primary-foreground">Go to Home</Link></section></PublicShell>; }
export function PublicAnnouncementPage() { const [, params] = useRoute("/a/:publicId"); return <PublicContentPage kind="announcement" publicId={params?.publicId ?? ""} label="Announcement" />; }
export function PublicAttendancePage() {
  const [, params] = useRoute("/attendance/:publicId");
  const publicId = params?.publicId ?? "";
  const attendance = trpc.foundation.publicAttendance.useQuery({ publicId }, { enabled: Boolean(publicId) });
  if (attendance.isLoading) return <PublicShell><p className="text-sm text-muted-foreground">Loading Attendance…</p></PublicShell>;
  if (!attendance.data?.available) return <PublicUnavailable />;
  const details = attendance.data.attendance;
  const totals = details.records.reduce((result, record) => {
    if (record.status === "PRESENT") result.present += 1;
    else if (record.status === "ABSENT") result.absent += 1;
    else if (record.status === "EXCUSED") result.excused += 1;
    else result.notSet += 1;
    return result;
  }, { present: 0, absent: 0, excused: 0, notSet: 0 });
  return <PublicShell><Link href={`/s/${details.subject.publicId}`} className="text-sm font-semibold text-primary">{details.subject.code} · {details.subject.name}</Link><article className="mt-5 rounded-[28px] border border-border bg-card p-6"><p className="text-sm font-semibold text-primary">Attendance · Version {details.version}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.035em]">Class Attendance</h1><p className="mt-2 text-sm text-muted-foreground">{new Date(details.startsAt).toLocaleString()}</p><p className="mt-5 text-sm leading-6 text-muted-foreground">This is the published final status list for this class session. Zoom participant input, automatic suggestions, and private excuse reasons are not shared here.</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><ReportMetric label="Present" value={totals.present} tone="text-emerald-300" /><ReportMetric label="Absent" value={totals.absent} tone="text-red-300" /><ReportMetric label="Excused" value={totals.excused} tone="text-sky-300" /><ReportMetric label="Not set" value={totals.notSet} tone="text-amber-300" /></div><div className="mt-6 space-y-2">{details.records.map(record => <div key={record.canonicalName} className="flex items-center justify-between gap-3 rounded-2xl bg-secondary px-4 py-3"><p className="min-w-0 truncate text-sm font-medium">{record.canonicalName}</p><span className={`shrink-0 text-xs font-semibold ${record.status === "PRESENT" ? "text-emerald-300" : record.status === "ABSENT" ? "text-red-300" : record.status === "EXCUSED" ? "text-sky-300" : "text-amber-300"}`}>{record.status.replace("_", " ")}</span></div>)}{!details.records.length ? <p className="rounded-2xl bg-secondary p-4 text-sm text-muted-foreground">No published Student statuses are available for this session.</p> : null}</div></article>{details.history.length ? <section className="mt-5 rounded-[28px] border border-border bg-card p-5"><div className="flex items-center gap-2"><History className="h-5 w-5 text-primary" /><h2 className="font-semibold">History</h2></div><ol className="mt-4 space-y-3">{details.history.map(entry => <li key={`${entry.version}-${entry.createdAt}`} className="rounded-2xl bg-secondary p-3"><p className="text-sm font-medium">Version {entry.version} · {entry.action}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{entry.summary}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(entry.createdAt).toLocaleDateString()}</p></li>)}</ol></section> : null}</PublicShell>;
}
export function PublicResourcePage() { const [, params] = useRoute("/r/:publicId"); return <PublicContentPage kind="resource" publicId={params?.publicId ?? ""} label="Resource" />; }
export function PublicQuestionPage() { const [, params] = useRoute("/q/:publicId"); return <PublicContentPage kind="question" publicId={params?.publicId ?? ""} label="Question & Answer" />; }
export function PublicReportPage() { const [, params] = useRoute("/reports/:publicId"); const publicId = params?.publicId ?? ""; const report = trpc.foundation.publicReport.useQuery({ publicId }, { enabled: Boolean(publicId) }); if (report.isLoading) return <PublicShell><p className="text-sm text-muted-foreground">Loading Report…</p></PublicShell>; if (!report.data?.available) return <PublicUnavailable />; const details = report.data.report; return <PublicShell><div className="print-hidden mt-5 flex justify-end"><button type="button" onClick={() => window.print()} className="inline-flex min-h-11 items-center rounded-2xl border border-border bg-card px-4 text-sm font-semibold text-foreground hover:border-primary/60 hover:text-primary">Print or save as PDF</button></div><article className="print-report mt-5 rounded-[28px] border border-border bg-card p-6"><p className="text-sm font-semibold text-primary">Report · Version {details.version}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.035em]">{details.title}</h1>{details.startsAt ? <p className="mt-2 text-sm text-muted-foreground">{new Date(details.startsAt).toLocaleString()}</p> : null}{details.totals ? <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><ReportMetric label="Present" value={details.totals.present} tone="text-emerald-300" /><ReportMetric label="Absent" value={details.totals.absent} tone="text-red-300" /><ReportMetric label="Excused" value={details.totals.excused} tone="text-sky-300" /><ReportMetric label="Not set" value={details.totals.notSet} tone="text-amber-300" /></div> : null}{details.subjects?.length ? <div className="mt-6 space-y-2">{details.subjects.map(subject => <div key={`${subject.subjectCode}-${subject.subjectName}`} className="rounded-2xl bg-secondary p-4"><p className="font-semibold">{subject.subjectName}</p><p className="mt-1 text-xs text-muted-foreground">{subject.subjectCode}</p><div className="mt-3 flex flex-wrap gap-2 text-xs font-semibold"><span className="text-emerald-300">{subject.present} present</span><span className="text-red-300">{subject.absent} absent</span><span className="text-sky-300">{subject.excused} excused</span><span className="text-amber-300">{subject.notSet} not set</span></div></div>)}</div> : null}<p className="mt-7 text-xs text-muted-foreground">This shared report includes aggregate Attendance only; private excuse reasons are not included.</p></article></PublicShell>; }

function PublicContentPage({ kind, publicId, label }: { kind: "announcement" | "resource" | "question"; publicId: string; label: string }) {
  const input = useMemo(() => ({ kind, publicId }), [kind, publicId]);
  const item = trpc.foundation.publicItem.useQuery(input, { enabled: Boolean(input.publicId) });
  const history = trpc.foundation.publicHistory.useQuery(input, { enabled: Boolean(input.publicId) && Boolean(item.data?.available) });
  if (item.isLoading) return <PublicShell><p className="text-sm text-muted-foreground">Loading {label}…</p></PublicShell>;
  if (!item.data?.available) return <PublicUnavailable />;
  const details = item.data.item;
  const visual = details.media ?? details.socialPreviewMedia;
  const visibleTitle = details.kind === "question" ? details.title.replace(/^(Official|Unofficial) answer — /, "") : details.title;
  const questionTags = details.kind === "question" ? details.tagsText?.split(",").map(tag => tag.trim()).filter(Boolean) ?? [] : [];
  return <PublicShell><Link href={`/s/${details.subject.publicId}`} className="linear-action inline-flex min-h-11 items-center px-2 text-sm font-medium text-primary hover:bg-secondary">{details.subject.code} · {details.subject.name}</Link><article className="linear-panel mt-5 overflow-hidden"><div className="p-5 sm:p-6"><p className="linear-label text-primary">{label} · Version {details.version}</p>{details.kind === "question" ? <span className={`mt-4 inline-flex min-h-8 items-center gap-1.5 rounded-full border px-3 text-xs font-medium ${details.isOfficial ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-200" : "border-amber-400/30 bg-amber-400/10 text-amber-200"}`}>{details.isOfficial ? <ShieldCheck className="h-3.5 w-3.5" /> : <CircleHelp className="h-3.5 w-3.5" />}{details.isOfficial ? "Official answer" : "Unofficial answer"}</span> : null}<h1 className="linear-title mt-3">{visibleTitle}</h1>{questionTags.length ? <div className="mt-3 flex flex-wrap gap-1">{questionTags.map(tag => <Badge key={tag} variant="outline" className="rounded-full text-xs">{tag}</Badge>)}</div> : null}{details.kind === "resource" && details.category ? <p className="mt-3 text-sm text-muted-foreground">{details.category}{details.sourceDomain ? ` · ${details.sourceDomain}` : ""}</p> : null}</div>{visual ? <img src={visual.url} alt={visual.altText ?? ""} className="max-h-[28rem] w-full object-cover" /> : null}<div className="p-5 pt-0 sm:p-6 sm:pt-0">{details.kind === "announcement" ? <AnnouncementPreview body={details.body} /> : <div className="whitespace-pre-wrap text-sm leading-7 text-foreground/90">{details.body}</div>}{details.kind === "resource" && details.destinationUrl ? <a href={details.destinationUrl} target="_blank" rel="noreferrer" className="linear-action mt-7 inline-flex min-h-11 items-center gap-2 bg-primary px-4 text-sm font-medium text-primary-foreground"><ExternalLink className="h-4 w-4" />Open Resource</a> : null}<p className="mt-7 text-xs text-muted-foreground">Published by the class secretary{details.publishedAt ? ` · ${new Date(details.publishedAt).toLocaleDateString()}` : ""}</p></div></article>{history.data?.available && history.data.history.length ? <section className="linear-panel mt-5 p-5"><div className="flex items-center gap-2"><History className="h-4 w-4 text-primary" /><h2 className="font-medium">History</h2></div><ol className="mt-4 space-y-3">{history.data.history.map(entry => <li key={`${entry.version}-${entry.createdAt}`} className="linear-panel-raised rounded-md p-3"><p className="text-sm font-medium">Version {entry.version} · {entry.action}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{entry.summary}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(entry.createdAt).toLocaleDateString()}</p></li>)}</ol></section> : null}</PublicShell>;
}

function AnnouncementMarkdown({ body }: { body: string }) {
  const lines = body.split("\n"); const blocks: React.ReactNode[] = []; let index = 0;
  while (index < lines.length) {
    const line = lines[index];
    if (!line.trim()) { index += 1; continue; }
    if (line.startsWith("## ")) { blocks.push(<h2 key={index} className="mt-7 text-xl font-semibold tracking-[-0.025em] first:mt-0"><InlineMarkdown text={line.slice(3)} /></h2>); index += 1; continue; }
    if (line.startsWith("> ")) { blocks.push(<blockquote key={index} className="my-5 border-l-2 border-primary pl-4 text-sm italic leading-7 text-muted-foreground"><InlineMarkdown text={line.slice(2)} /></blockquote>); index += 1; continue; }
    if (line.startsWith("- ")) { const entries: string[] = []; while (index < lines.length && lines[index].startsWith("- ")) { entries.push(lines[index].slice(2)); index += 1; } blocks.push(<ul key={index} className="my-5 list-disc space-y-2 pl-5 text-sm leading-7 text-foreground/90">{entries.map((entry, entryIndex) => <li key={entryIndex}><InlineMarkdown text={entry} /></li>)}</ul>); continue; }
    if (/^\d+\.\s/.test(line)) { const entries: string[] = []; while (index < lines.length && /^\d+\.\s/.test(lines[index])) { entries.push(lines[index].replace(/^\d+\.\s/, "")); index += 1; } blocks.push(<ol key={index} className="my-5 list-decimal space-y-2 pl-5 text-sm leading-7 text-foreground/90">{entries.map((entry, entryIndex) => <li key={entryIndex}><InlineMarkdown text={entry} /></li>)}</ol>); continue; }
    blocks.push(<p key={index} className="mb-4 text-sm leading-7 text-foreground/90"><InlineMarkdown text={line} /></p>); index += 1;
  }
  return <div>{blocks}</div>;
}

function InlineMarkdown({ text }: { text: string }) {
  return <>{text.split(/(\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)|\*\*([^*]+)\*\*|\*([^*]+)\*)/g).filter(Boolean).map((part, index) => {
    const link = part.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/); if (link) return <a key={index} href={link[2]} target="_blank" rel="noreferrer" className="font-medium text-primary underline underline-offset-4">{link[1]}</a>;
    const bold = part.match(/^\*\*([^*]+)\*\*$/); if (bold) return <strong key={index}>{bold[1]}</strong>;
    const italic = part.match(/^\*([^*]+)\*$/); if (italic) return <em key={index}>{italic[1]}</em>;
    return part;
  })}</>;
}

export function PublicShell({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-background px-5 py-5 text-foreground sm:px-8 sm:py-9"><div className="mx-auto max-w-3xl"><header className="mb-8 flex min-h-14 items-center justify-between gap-4 border-b border-border px-1 pb-3"><Link href="/" className="inline-flex items-center gap-2 rounded-md text-sm font-semibold tracking-[-0.03em] text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="grid h-8 w-8 place-items-center rounded-md bg-primary text-xs font-semibold text-primary-foreground">CM</span><span>Class Management</span></Link><span className="rounded-full border border-primary/25 bg-primary/10 px-2.5 py-1 text-[11px] font-medium tracking-wide text-primary">VIEW ONLY</span></header><div className="pb-8">{children}</div><footer className="border-t border-border pt-5 text-center text-xs leading-5 text-muted-foreground">Shared class information · View only · Managed by the class secretary</footer></div></main>; }
function ReportMetric({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className="linear-panel-raised rounded-md p-4"><p className="text-sm text-muted-foreground">{label}</p><p className={`mt-2 text-3xl font-semibold ${tone}`}>{value}</p></div>; }
function PublicAttendanceList({ items }: { items: Array<{ publicId: string; startsAt: Date }> }) { return <section className="linear-panel p-5"><BookOpen className="h-4 w-4 text-primary" /><h2 className="mt-4 font-medium">Attendance</h2>{items.length ? <div className="mt-3 space-y-2">{items.map(item => <Link key={item.publicId} href={`/attendance/${item.publicId}`} className="linear-panel-raised block rounded-md px-3 py-2 text-sm font-medium hover:text-primary">{new Date(item.startsAt).toLocaleDateString()}</Link>)}</div> : <p className="mt-1 text-sm leading-6 text-muted-foreground">Published class-session Attendance will appear here.</p>}</section>; }
function PublicResourceCards({ items }: { items: Array<{ publicId: string; title: string; description: string; category: string; resourceType: string; sourceDomain: string; thumbnail: { url: string; altText: string | null } | null }> }) { return <section className="rounded-[24px] border border-border bg-card p-5 sm:col-span-2"><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-primary" /><h2 className="font-semibold">Resources</h2></div>{items.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{items.map(item => <Link key={item.publicId} href={`/r/${item.publicId}`} className="group overflow-hidden rounded-2xl border border-border bg-secondary transition-colors hover:border-primary/50 hover:bg-accent"><div className="aspect-[16/8] bg-muted/55">{item.thumbnail ? <img src={item.thumbnail.url} alt={item.thumbnail.altText ?? ""} className="h-full w-full object-cover" /> : <div className="flex h-full items-end p-4"><span className="apple-material rounded-full px-3 py-1 text-xs font-semibold text-foreground">{item.resourceType}</span></div>}</div><div className="p-4"><p className="text-sm font-semibold group-hover:text-primary">{item.title}</p><p className="mt-2 line-clamp-2 text-sm leading-5 text-muted-foreground">{item.description}</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-muted-foreground"><span>{item.category}</span><span aria-hidden="true">·</span><span>{item.sourceDomain}</span></div></div></Link>)}</div> : <p className="mt-2 text-sm leading-6 text-muted-foreground">Class links and materials will appear here.</p>}</section>; }
function PublicLink({ icon: Icon, title, body }: { icon: typeof BookOpen; title: string; body: string }) { return <section className="rounded-[24px] border border-border bg-card p-5"><Icon className="h-5 w-5 text-primary" /><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{body}</p></section>; }
function PublicList({ icon: Icon, title, items, pathPrefix, empty, allHref }: { icon: typeof BookOpen; title: string; items: Array<{ publicId: string; title: string }>; pathPrefix: string; empty: string; allHref?: string }) { return <section className="linear-panel p-5"><Icon className="h-4 w-4 text-primary" /><h2 className="mt-4 font-medium">{title}</h2>{items.length ? <div className="mt-3 space-y-2">{items.map(item => <Link key={item.publicId} href={`${pathPrefix}${item.publicId}`} className="linear-panel-raised block rounded-md px-3 py-2 text-sm font-medium hover:text-primary">{item.title}</Link>)}</div> : <p className="mt-1 text-sm leading-6 text-muted-foreground">{empty}</p>}{allHref ? <Link href={allHref} className="mt-3 inline-flex min-h-11 items-center text-sm font-medium text-primary">Browse all answers</Link> : null}</section>; }
