import { AnnouncementPreview } from "@/components/AnnouncementPreview";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { BookOpen, CalendarDays, CircleAlert, CircleHelp, ExternalLink, History, MessageCircleMore, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useRoute } from "wouter";

const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export function PublicSubjectPage() {
  const [, params] = useRoute("/s/:publicId");
  const input = useMemo(() => ({ publicId: params?.publicId ?? "" }), [params?.publicId]);
  const subject = trpc.foundation.publicSubject.useQuery(input, { enabled: Boolean(input.publicId) });
  if (subject.isLoading) return <PublicShell><ReaderLoading label="Subject" /></PublicShell>;
  if (subject.isError) return <PublicShell><ReaderFailure /></PublicShell>;
  if (!subject.data?.available) return <PublicUnavailable />;
  const details = subject.data.subject;
  const schedule = details.meetingDays.length ? details.meetingDays.map(day => `${dayNames[day.weekday]}${day.startTime ? ` · ${day.startTime}${day.endTime ? `–${day.endTime}` : ""}` : ""}`).join(" · ") : "Schedule will be shared soon.";
  return <PublicShell><section className="signal-panel border-t-2 border-primary p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="signal-kicker">{details.code}</p><h1 className="signal-title mt-3">{details.name}</h1><p className="mt-3 text-sm text-muted-foreground">Professor {details.professorName}</p></div><div className="signal-inset min-w-52 p-4"><p className="signal-kicker">Class rhythm</p><p className="mt-2 text-sm font-semibold leading-6">{schedule}</p></div></div></section>{details.noClass ? <section className="mt-5 border-l-2 border-amber-300 bg-amber-300/10 p-4"><div className="flex gap-3"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-300" /><div><h2 className="font-semibold">No Class</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{new Date(details.noClass.startsAt).toLocaleDateString()} — {details.noClass.reason}</p></div></div></section> : null}<section className="mt-8"><p className="signal-kicker">Class record</p><h2 className="signal-heading mt-2">What the secretary has published.</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><PublicAttendanceList items={details.latest.attendance} /><PublicList icon={MessageCircleMore} title="Questions & Answers" items={details.latest.questions} pathPrefix="/q/" empty="Shared answers will appear here." allHref={`/s/${details.publicId}/questions`} /><PublicList icon={ExternalLink} title="Announcements" items={details.latest.announcements} pathPrefix="/a/" empty="Official updates will appear here." /><PublicResourceCards items={details.latest.resources} /></div></section></PublicShell>;
}

export function PublicSubjectQuestionsPage() {
  const [, params] = useRoute("/s/:publicId/questions");
  const publicId = params?.publicId ?? "";
  const [searchDraft, setSearchDraft] = useState("");
  const [search, setSearch] = useState("");
  const questions = trpc.foundation.publicQuestions.useQuery({ publicId, query: search || undefined }, { enabled: Boolean(publicId) });
  if (questions.isLoading) return <PublicShell><ReaderLoading label="Questions & Answers" /></PublicShell>;
  if (questions.isError) return <PublicShell><ReaderFailure /></PublicShell>;
  if (!questions.data?.available) return <PublicUnavailable />;
  const { subject, questions: items } = questions.data;
  return <PublicShell><BackToSubject subject={subject} /><section className="mt-6 border-y border-border py-5"><p className="signal-kicker">Shared answers</p><h1 className="signal-title mt-2">Questions & Answers</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Search published answers by topic, question, answer, or tag.</p><form className="mt-5 flex gap-2" onSubmit={event => { event.preventDefault(); setSearch(searchDraft.trim()); }}><input type="search" value={searchDraft} onChange={event => setSearchDraft(event.target.value)} className="min-h-11 flex-1 rounded-xl border border-input bg-card px-3 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder="Search published answers" aria-label="Search published answers" /><button type="submit" className="signal-action min-h-11 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Search</button></form>{search ? <p className="mt-3 text-sm text-muted-foreground">{items.length} {items.length === 1 ? "answer" : "answers"} for “{search}”</p> : null}</section><section className="divide-y divide-border border-b border-border">{items.map(item => { const tags = item.tagsText?.split(",").map(tag => tag.trim()).filter(Boolean) ?? []; return <Link key={item.publicId} href={`/q/${item.publicId}`} className="block py-5 hover:bg-secondary/40"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className={`rounded-full text-xs ${item.isOfficial ? "border-emerald-400/30 text-emerald-200" : "border-amber-400/30 text-amber-200"}`}>{item.isOfficial ? "Official answer" : "Unofficial answer"}</Badge>{tags.map(tag => <Badge key={tag} variant="outline" className="rounded-full text-xs">{tag}</Badge>)}</div><h2 className="mt-3 text-lg font-semibold">{item.question}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-muted-foreground">{item.answer}</p>{item.publishedAt ? <p className="mt-3 text-xs text-muted-foreground">Published {new Date(item.publishedAt).toLocaleDateString()}</p> : null}</Link>; })}{!items.length ? <div className="py-10 text-center"><h2 className="font-semibold">No published answers found</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Try another topic or return to the Subject Home.</p></div> : null}</section></PublicShell>;
}

export function PublicUnavailable() { return <PublicShell><section className="signal-panel border-t-2 border-primary p-7 text-center"><CircleAlert className="mx-auto h-6 w-6 text-muted-foreground" /><h1 className="signal-heading mt-4">This page is not available</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">The link may be incomplete, unpublished, or no longer shared.</p><Link href="/" className="signal-action mt-6 inline-flex min-h-11 items-center rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Go to Home</Link></section></PublicShell>; }
export function PublicAnnouncementPage() { const [, params] = useRoute("/a/:publicId"); return <PublicContentPage kind="announcement" publicId={params?.publicId ?? ""} label="Announcement" />; }
export function PublicResourcePage() { const [, params] = useRoute("/r/:publicId"); return <PublicContentPage kind="resource" publicId={params?.publicId ?? ""} label="Resource" />; }
export function PublicQuestionPage() { const [, params] = useRoute("/q/:publicId"); return <PublicContentPage kind="question" publicId={params?.publicId ?? ""} label="Question & Answer" />; }

export function PublicAttendancePage() {
  const [, params] = useRoute("/attendance/:publicId");
  const publicId = params?.publicId ?? "";
  const attendance = trpc.foundation.publicAttendance.useQuery({ publicId }, { enabled: Boolean(publicId) });
  if (attendance.isLoading) return <PublicShell><ReaderLoading label="Attendance" /></PublicShell>;
  if (attendance.isError) return <PublicShell><ReaderFailure /></PublicShell>;
  if (!attendance.data?.available) return <PublicUnavailable />;
  const details = attendance.data.attendance;
  const totals = details.records.reduce((result, record) => { if (record.status === "PRESENT") result.present += 1; else if (record.status === "ABSENT") result.absent += 1; else if (record.status === "EXCUSED") result.excused += 1; else result.notSet += 1; return result; }, { present: 0, absent: 0, excused: 0, notSet: 0 });
  return <PublicShell><BackToSubject subject={details.subject} /><article className="mt-6"><p className="signal-kicker">Attendance · Version {details.version}</p><h1 className="signal-title mt-2">Class Attendance</h1><p className="mt-2 text-sm text-muted-foreground">{new Date(details.startsAt).toLocaleString()}</p><p className="mt-5 text-sm text-muted-foreground">Published class status.</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><ReportMetric label="Present" value={totals.present} tone="text-emerald-300" /><ReportMetric label="Absent" value={totals.absent} tone="text-red-300" /><ReportMetric label="Excused" value={totals.excused} tone="text-sky-300" /><ReportMetric label="Not set" value={totals.notSet} tone="text-amber-300" /></div><div className="mt-7 divide-y divide-border">{details.records.map(record => <div key={record.canonicalName} className="flex items-center justify-between gap-3 py-4"><p className="min-w-0 truncate text-sm font-semibold">{record.canonicalName}</p><span className={`shrink-0 text-xs font-bold ${statusTone(record.status)}`}>{record.status.replace("_", " ")}</span></div>)}{!details.records.length ? <p className="py-5 text-sm text-muted-foreground">No Student statuses published.</p> : null}</div></article><HistoryLedger entries={details.history} /></PublicShell>;
}

export function PublicReportPage() {
  const [, params] = useRoute("/reports/:publicId");
  const publicId = params?.publicId ?? "";
  const report = trpc.foundation.publicReport.useQuery({ publicId }, { enabled: Boolean(publicId) });
  if (report.isLoading) return <PublicShell><ReaderLoading label="Report" /></PublicShell>;
  if (report.isError) return <PublicShell><ReaderFailure /></PublicShell>;
  if (!report.data?.available) return <PublicUnavailable />;
  const details = report.data.report;
  return <PublicShell><div className="print-hidden flex justify-end"><button type="button" onClick={() => window.print()} className="signal-action inline-flex min-h-11 items-center rounded-xl border border-border px-4 text-sm font-semibold hover:bg-secondary hover:text-primary">Print or save as PDF</button></div><article className="print-report mt-6"><p className="signal-kicker">Report · Version {details.version}</p><h1 className="signal-title mt-2">{details.title}</h1>{details.startsAt ? <p className="mt-2 text-sm text-muted-foreground">{new Date(details.startsAt).toLocaleString()}</p> : null}{details.totals ? <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><ReportMetric label="Present" value={details.totals.present} tone="text-emerald-300" /><ReportMetric label="Absent" value={details.totals.absent} tone="text-red-300" /><ReportMetric label="Excused" value={details.totals.excused} tone="text-sky-300" /><ReportMetric label="Not set" value={details.totals.notSet} tone="text-amber-300" /></div> : null}{details.subjects?.length ? <div className="mt-7 divide-y divide-border">{details.subjects.map(subject => <div key={`${subject.subjectCode}-${subject.subjectName}`} className="py-5"><p className="font-semibold">{subject.subjectName}</p><p className="mt-1 text-xs text-muted-foreground">{subject.subjectCode}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs font-bold"><span className="text-emerald-300">{subject.present} present</span><span className="text-red-300">{subject.absent} absent</span><span className="text-sky-300">{subject.excused} excused</span><span className="text-amber-300">{subject.notSet} not set</span></div></div>)}</div> : null}<p className="mt-7 text-xs text-muted-foreground">Aggregate Attendance only.</p></article></PublicShell>;
}

function PublicContentPage({ kind, publicId, label }: { kind: "announcement" | "resource" | "question"; publicId: string; label: string }) {
  const input = useMemo(() => ({ kind, publicId }), [kind, publicId]);
  const item = trpc.foundation.publicItem.useQuery(input, { enabled: Boolean(input.publicId) });
  const history = trpc.foundation.publicHistory.useQuery(input, { enabled: Boolean(input.publicId) && Boolean(item.data?.available) });
  if (item.isLoading) return <PublicShell><ReaderLoading label={label} /></PublicShell>;
  if (item.isError) return <PublicShell><ReaderFailure /></PublicShell>;
  if (!item.data?.available) return <PublicUnavailable />;
  const details = item.data.item;
  const visual = details.media ?? details.socialPreviewMedia;
  const visibleTitle = details.kind === "question" ? details.title.replace(/^(Official|Unofficial) answer — /, "") : details.title;
  const tags = details.kind === "question" ? details.tagsText?.split(",").map(tag => tag.trim()).filter(Boolean) ?? [] : [];
  return <PublicShell><BackToSubject subject={details.subject} /><article className="signal-panel mt-6 overflow-hidden border-t-2 border-primary"><div className="p-5 sm:p-7"><p className="signal-kicker">{label} · Version {details.version}</p>{details.kind === "question" ? <span className={`mt-4 inline-flex min-h-8 items-center gap-1.5 rounded-full border px-3 text-xs font-semibold ${details.isOfficial ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-200" : "border-amber-400/30 bg-amber-400/10 text-amber-200"}`}>{details.isOfficial ? <ShieldCheck className="h-3.5 w-3.5" /> : <CircleHelp className="h-3.5 w-3.5" />}{details.isOfficial ? "Official answer" : "Unofficial answer"}</span> : null}<h1 className="signal-title mt-3">{visibleTitle}</h1>{tags.length ? <div className="mt-3 flex flex-wrap gap-1">{tags.map(tag => <Badge key={tag} variant="outline" className="rounded-full text-xs">{tag}</Badge>)}</div> : null}{details.kind === "resource" && details.category ? <p className="mt-3 text-sm text-muted-foreground">{details.category}{details.sourceDomain ? ` · ${details.sourceDomain}` : ""}</p> : null}</div>{visual ? <img src={visual.url} alt={visual.altText ?? ""} className="max-h-[28rem] w-full object-cover" /> : null}<div className="p-5 pt-0 sm:p-7 sm:pt-0"><div className="border-t border-border pt-6">{details.kind === "announcement" ? <AnnouncementPreview body={details.body} /> : <div className="whitespace-pre-wrap text-sm leading-7 text-foreground/90">{details.body}</div>}</div>{details.kind === "resource" && details.destinationUrl ? <a href={details.destinationUrl} target="_blank" rel="noreferrer" className="signal-action mt-7 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground"><ExternalLink className="h-4 w-4" />Open Resource</a> : null}<p className="mt-7 text-xs text-muted-foreground">Published by the class secretary{details.publishedAt ? ` · ${new Date(details.publishedAt).toLocaleDateString()}` : ""}</p></div></article><HistoryLedger entries={history.data?.available ? history.data.history : []} /></PublicShell>;
}

export function PublicShell({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-background px-5 py-5 text-foreground sm:px-8 sm:py-9"><div className="mx-auto max-w-3xl"><header className="mb-8 flex min-h-14 items-center justify-between gap-4 border-b border-border pb-3"><Link href="/" className="signal-action inline-flex items-center gap-2 text-sm font-bold tracking-[-0.03em] text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="grid h-8 w-8 place-items-center rounded-xl bg-primary text-xs font-extrabold text-primary-foreground">CM</span><span>Class Management</span></Link><span className="rounded-full border border-primary/25 bg-primary/10 px-2.5 py-1 text-[11px] font-semibold tracking-wide text-primary">VIEW ONLY</span></header><div className="pb-8">{children}</div><footer className="border-t border-border pt-5 text-center text-xs text-muted-foreground">View-only class information</footer></div></main>; }

function BackToSubject({ subject }: { subject: { publicId: string; code: string; name: string } }) { return <Link href={`/s/${subject.publicId}`} className="signal-action inline-flex min-h-11 items-center px-2 text-sm font-semibold text-primary hover:bg-secondary">{subject.code} · {subject.name}</Link>; }
function ReaderLoading({ label }: { label: string }) { return <p className="text-sm text-muted-foreground">Loading {label}…</p>; }
function ReaderFailure() { return <section className="signal-panel border-t-2 border-primary p-7 text-center"><CircleAlert className="mx-auto h-6 w-6 text-muted-foreground" /><h1 className="signal-heading mt-4">Unable to load this page</h1><p className="mt-2 text-sm text-muted-foreground">Please try again in a moment.</p><button type="button" onClick={() => window.location.reload()} className="signal-action mt-6 inline-flex min-h-11 items-center rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Try again</button></section>; }
function statusTone(status: "PRESENT" | "ABSENT" | "EXCUSED" | "NOT_SET") { return status === "PRESENT" ? "text-emerald-300" : status === "ABSENT" ? "text-red-300" : status === "EXCUSED" ? "text-sky-300" : "text-amber-300"; }
function ReportMetric({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className="signal-inset p-4"><p className="text-sm text-muted-foreground">{label}</p><p className={`mt-2 text-3xl font-semibold ${tone}`}>{value}</p></div>; }
function HistoryLedger({ entries }: { entries: Array<{ version: number; action: string; summary: string; createdAt: Date }> }) { if (!entries.length) return null; return <section className="mt-7 border-t border-border pt-5"><div className="flex items-center gap-2"><History className="h-4 w-4 text-primary" /><h2 className="font-semibold">History</h2></div><ol className="mt-4 divide-y divide-border">{entries.map(entry => <li key={`${entry.version}-${entry.createdAt}`} className="py-4"><p className="text-sm font-semibold">Version {entry.version} · {entry.action}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{entry.summary}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(entry.createdAt).toLocaleDateString()}</p></li>)}</ol></section>; }
function PublicAttendanceList({ items }: { items: Array<{ publicId: string; startsAt: Date }> }) { return <ReaderSection icon={BookOpen} title="Attendance"><p className="text-sm leading-6 text-muted-foreground">Review the final class-session records shared by the secretary.</p>{items.length ? <div className="mt-4 divide-y divide-border">{items.map(item => <Link key={item.publicId} href={`/attendance/${item.publicId}`} className="signal-action flex min-h-11 items-center py-3 text-sm font-semibold hover:text-primary">{new Date(item.startsAt).toLocaleDateString()}</Link>)}</div> : <p className="mt-3 text-sm leading-6 text-muted-foreground">Published class-session Attendance will appear here.</p>}</ReaderSection>; }
function PublicResourceCards({ items }: { items: Array<{ publicId: string; title: string; description: string; category: string; resourceType: string; sourceDomain: string; thumbnail: { url: string; altText: string | null } | null }> }) { return <ReaderSection icon={BookOpen} title="Resources" className="sm:col-span-2">{items.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{items.map(item => <Link key={item.publicId} href={`/r/${item.publicId}`} className="signal-inset group overflow-hidden hover:border-primary/60">{item.thumbnail ? <img src={item.thumbnail.url} alt={item.thumbnail.altText ?? ""} className="aspect-[16/8] w-full object-cover" /> : <div className="flex aspect-[16/8] items-end p-4"><span className="rounded-full border border-border px-3 py-1 text-xs font-semibold">{item.resourceType}</span></div>}<div className="p-4"><p className="text-sm font-semibold group-hover:text-primary">{item.title}</p><p className="mt-2 line-clamp-2 text-sm leading-5 text-muted-foreground">{item.description}</p><p className="mt-3 text-xs text-muted-foreground">{item.category} · {item.sourceDomain}</p></div></Link>)}</div> : <p className="mt-3 text-sm leading-6 text-muted-foreground">Class links and materials will appear here.</p>}</ReaderSection>; }
function PublicList({ icon, title, items, pathPrefix, empty, allHref }: { icon: typeof BookOpen; title: string; items: Array<{ publicId: string; title: string }>; pathPrefix: string; empty: string; allHref?: string }) { return <ReaderSection icon={icon} title={title}>{items.length ? <div className="mt-4 divide-y divide-border">{items.map(item => <Link key={item.publicId} href={`${pathPrefix}${item.publicId}`} className="signal-action flex min-h-11 items-center py-3 text-sm font-semibold hover:text-primary">{item.title}</Link>)}</div> : <p className="mt-3 text-sm leading-6 text-muted-foreground">{empty}</p>}{allHref ? <Link href={allHref} className="signal-action mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-primary">Browse all answers</Link> : null}</ReaderSection>; }
function ReaderSection({ icon: Icon, title, children, className = "" }: { icon: typeof BookOpen; title: string; children: React.ReactNode; className?: string }) { return <section className={`signal-panel p-5 ${className}`}><Icon className="h-4 w-4 text-primary" /><h2 className="mt-4 font-semibold">{title}</h2>{children}</section>; }
