import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ChartNoAxesCombined, CheckCircle2, CircleDashed, XCircle } from "lucide-react";
import { useSearch } from "wouter";

export default function ReportsPage() {
  const search = useSearch();
  const sessionId = Number(new URLSearchParams(search).get("sessionId"));
  const report = trpc.reports.allSubjectAttendance.useQuery();
  const classReport = trpc.reports.classAttendance.useQuery({ sessionId }, { enabled: Number.isInteger(sessionId) && sessionId > 0 });
  const totals = (report.data ?? []).reduce((sum, item) => ({ present: sum.present + item.present, absent: sum.absent + item.absent, notSet: sum.notSet + item.notSet }), { present: 0, absent: 0, notSet: 0 });
  return <DashboardLayout><section className="mx-auto max-w-5xl"><p className="text-sm font-semibold text-primary">Secretary reports</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Reports</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Review Attendance across active Subjects and individual class sessions.</p>{classReport.data ? <section className="mt-6 rounded-[28px] border border-primary/30 bg-primary/5 p-5"><p className="text-sm font-semibold text-primary">Class Attendance</p><h2 className="mt-2 text-xl font-semibold">{classReport.data.subjectName} · {classReport.data.subjectCode}</h2><p className="mt-1 text-sm text-muted-foreground">{new Date(classReport.data.startsAt).toLocaleString()}</p><div className="mt-4 flex flex-wrap gap-2"><Badge variant="secondary" className="rounded-full text-emerald-300">{classReport.data.present} present</Badge><Badge variant="secondary" className="rounded-full text-red-300">{classReport.data.absent} absent</Badge><Badge variant="secondary" className="rounded-full text-amber-300">{classReport.data.notSet} not set</Badge></div></section> : null}<div className="mt-7 grid gap-3 sm:grid-cols-3"><Metric icon={CheckCircle2} label="Present" value={totals.present} tone="text-emerald-300" /><Metric icon={XCircle} label="Absent" value={totals.absent} tone="text-red-300" /><Metric icon={CircleDashed} label="Not set" value={totals.notSet} tone="text-amber-300" /></div><section className="mt-6 rounded-[28px] border border-border bg-card p-5"><div className="flex items-center gap-2"><ChartNoAxesCombined className="h-5 w-5 text-primary" /><h2 className="font-semibold">All Subject Attendance</h2></div><div className="mt-4 space-y-2">{report.isLoading ? <p className="text-sm text-muted-foreground">Loading reports…</p> : null}{report.data?.map(item => <div key={item.subjectId} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-secondary p-4"><div><p className="font-semibold">{item.subjectName}</p><p className="mt-1 text-xs text-muted-foreground">{item.subjectCode}</p></div><div className="flex gap-2 text-xs font-semibold"><Badge variant="secondary" className="rounded-full text-emerald-300">{item.present} present</Badge><Badge variant="secondary" className="rounded-full text-red-300">{item.absent} absent</Badge><Badge variant="secondary" className="rounded-full text-amber-300">{item.notSet} not set</Badge></div></div>)}{!report.isLoading && !report.data?.length ? <p className="py-10 text-center text-sm text-muted-foreground">Add active Subjects and Attendance records to see the end-of-exams summary.</p> : null}</div></section></section></DashboardLayout>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof CheckCircle2; label: string; value: number; tone: string }) { return <section className="rounded-2xl border border-border bg-card p-4"><Icon className={`h-5 w-5 ${tone}`} /><p className="mt-4 text-sm text-muted-foreground">{label}</p><p className={`mt-1 text-3xl font-semibold ${tone}`}>{value}</p></section>; }
