import DashboardLayout from "@/components/DashboardLayout";
import { RecordStatusBadge } from "@/components/RecordStatusBadge";
import { WorkspacePageHeader } from "@/components/WorkspacePageHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Archive, ArrowRight, BookOpen, ChartNoAxesCombined, Settings } from "lucide-react";
import { Link } from "wouter";

const pageInfo = { subjects: { icon: BookOpen, title: "Subjects", body: "Manage each class separately." }, reports: { icon: ChartNoAxesCombined, title: "Reports", body: "Create and share class reports." }, settings: { icon: Settings, title: "Settings", body: "Manage your class workspace." } } as const;

export function SecretaryDashboard() {
  const owner = trpc.foundation.owner.getContext.useQuery(); const subjects = trpc.subjects.list.useQuery(); const reports = trpc.reports.list.useQuery();
  const activeSubjects = subjects.data?.filter(subject => subject.status === "active").length ?? 0; const sharedSubjects = subjects.data?.filter(subject => subject.status === "active" && subject.publishState === "published").length ?? 0; const publishedReports = reports.data?.filter(report => report.publishState === "published").length ?? 0; const archivedSubjects = subjects.data?.filter(subject => subject.status === "archived").length ?? 0;
  return <DashboardLayout><section className="mx-auto max-w-6xl pb-10"><header className="border-b border-border pb-7"><p className="signal-kicker">Secretary workspace</p><div className="mt-3 flex flex-wrap items-end justify-between gap-6"><h1 className="signal-title">Class operations</h1><div className="border-l-2 border-primary pl-4"><p className="signal-kicker">Active Subjects</p><p className="mt-1 font-[Manrope] text-4xl font-extrabold tracking-[-0.07em]">{activeSubjects}</p></div></div></header><div className="mt-7 grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(16rem,.7fr)]"><section className="signal-panel border-l-2 border-l-primary p-6 sm:p-8"><p className="signal-kicker">Start here</p><h2 className="signal-heading mt-2 text-2xl">Open a class desk.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Add a session, take Attendance, or post an update.</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild><Link href="/app/subjects">Open Subjects <ArrowRight className="h-4 w-4" /></Link></Button><Button asChild variant="outline"><Link href="/app/settings">Settings</Link></Button></div></section><section className="border-y border-border py-5 lg:border-y-0 lg:border-l lg:pl-6"><p className="signal-kicker">Class status</p><div className="mt-4 space-y-4"><PulseRow label="Shared" value={sharedSubjects} tone="text-emerald-300" /><PulseRow label="Reports" value={publishedReports} tone="text-primary" /><PulseRow label="Archived" value={archivedSubjects} tone="text-muted-foreground" /></div></section></div><section className="signal-inset mt-8 flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">Private work stays private.</p><p className="mt-1 text-sm text-muted-foreground">Published pages are view-only.</p></div><Button asChild variant="outline"><Link href="/app/archive"><Archive className="h-4 w-4" />Archive</Link></Button></section></section></DashboardLayout>;
}

export function SecretarySettingsPage() {
  const subjects = trpc.subjects.list.useQuery(); const activeSubjects = subjects.data?.filter(subject => subject.status === "active") ?? [];
  return <DashboardLayout><section className="mx-auto max-w-4xl"><WorkspacePageHeader eyebrow="Private workspace" title="Settings" description="Choose a Subject to edit its details or sharing." /><section className="signal-panel mt-7"><div className="border-b border-border px-5 py-5 sm:px-6"><p className="signal-kicker">Subject controls</p><h2 className="mt-2 text-xl font-bold tracking-[-0.04em]">Choose a class.</h2></div><div className="divide-y divide-border">{activeSubjects.map(subject => <Link key={subject.id} href={`/app/subjects?subject=${subject.id}`} className="signal-action group flex min-h-20 items-start gap-4 px-5 py-5 hover:bg-secondary/60 sm:px-6"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-accent text-primary"><BookOpen className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{subject.name}</p><RecordStatusBadge tone={subject.publishState === "published" ? "published" : "draft"}>{subject.publishState}</RecordStatusBadge></div><p className="mt-1 text-sm text-muted-foreground">{subject.code} · {subject.professorName}</p></div><ArrowRight className="mt-3 h-4 w-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5 group-hover:text-primary" /></Link>)}{subjects.isLoading ? <p className="px-6 py-10 text-center text-sm text-muted-foreground">Loading Subjects…</p> : null}{!subjects.isLoading && !activeSubjects.length ? <div className="px-6 py-10 text-center"><Settings className="mx-auto h-5 w-5 text-primary" /><h2 className="mt-4 font-semibold">No active Subjects</h2><p className="mt-2 text-sm text-muted-foreground">Create a Subject to manage it here.</p><Button asChild className="mt-5"><Link href="/app/subjects">Open Subjects</Link></Button></div> : null}</div></section></section></DashboardLayout>;
}

export function SecretaryPlaceholder({ page }: { page: keyof typeof pageInfo }) { const content = pageInfo[page]; const Icon = content.icon; return <DashboardLayout><section className="mx-auto grid min-h-[55vh] max-w-2xl place-items-center"><div className="signal-panel w-full border-t-2 border-primary p-7 text-center"><span className="mx-auto grid h-11 w-11 place-items-center rounded-2xl bg-accent text-primary"><Icon className="h-5 w-5" /></span><h1 className="signal-heading mt-5">{content.title}</h1><p className="mx-auto mt-3 max-w-md text-sm text-muted-foreground">{content.body}</p><Button asChild className="mt-6"><Link href="/app">Back to Dashboard</Link></Button></div></section></DashboardLayout>; }
function PulseRow({ label, value, tone = "text-foreground" }: { label: string; value: number; tone?: string }) { return <div className="flex items-baseline justify-between gap-3 border-b border-border pb-3"><p className="text-sm text-muted-foreground">{label}</p><p className={`font-[Manrope] text-2xl font-extrabold tracking-[-0.06em] ${tone}`}>{value}</p></div>; }
