import { formatFileSize, isPublicImageMimeType } from "@shared/mediaPolicy";
import { Download, FileText, Image } from "lucide-react";

export type PublicResourceAttachment = { id: number; url: string; originalName: string; mimeType: string; byteSize: number; altText: string | null };

export function PublicResourceAttachments({ attachments }: { attachments?: PublicResourceAttachment[] }) {
  if (!attachments?.length) return null;
  return <section className="mt-7 border-t border-border pt-6"><div className="flex items-center gap-2"><FileText className="size-4 text-primary" /><div><h2 className="font-semibold">Attached course files</h2><p className="mt-0.5 text-xs text-muted-foreground">{attachments.length} file{attachments.length === 1 ? "" : "s"} included with this Resource.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{attachments.map(attachment => { const image = isPublicImageMimeType(attachment.mimeType); return <a key={attachment.id} href={attachment.url} target="_blank" rel="noreferrer" className="signal-action group overflow-hidden rounded-xl border border-border bg-secondary/35 hover:border-primary/55 hover:bg-secondary/60">{image ? <img src={attachment.url} alt={attachment.altText ?? ""} className="h-32 w-full object-cover" /> : null}<span className="flex min-h-16 items-center gap-3 p-3">{image ? <span className="grid size-9 shrink-0 place-items-center rounded-lg bg-accent text-primary"><Image className="size-4" /></span> : <span className="grid size-9 shrink-0 place-items-center rounded-lg bg-accent text-primary"><FileText className="size-4" /></span>}<span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-foreground">{attachment.originalName}</span><span className="mt-0.5 block text-xs text-muted-foreground">{formatFileSize(attachment.byteSize)} · {image ? "Open image" : "Download file"}</span></span><Download className="size-4 shrink-0 text-primary" /></span></a>; })}</div></section>;
}
